#!/bin/sh
# Upload file: mosquitto.conf
# Auto-generated by create-application
set -eu

upload_pre_start_file \
  "{{ upload_mosquitto_conf_content }}" \
  "{{ upload_mosquitto_conf_destination }}" \
  "mosquitto.conf" \
  "{{ shared_volpath }}" \
  "{{ hostname }}" \
  "{{ uid }}" \
  "{{ gid }}" \
  "{{ mapped_uid }}" \
  "{{ mapped_gid }}"

upload_output_result "upload_mosquitto_conf_uploaded"
