#!/bin/sh
# Upload file: ca.crt
# Auto-generated by create-application
set -eu

upload_pre_start_file \
  "{{ upload_ca_content }}" \
  "{{ upload_ca_destination }}" \
  "ca.crt" \
  "{{ shared_volpath }}" \
  "{{ hostname }}" \
  "{{ uid }}" \
  "{{ gid }}" \
  "{{ mapped_uid }}" \
  "{{ mapped_gid }}"

upload_output_result "upload_ca_uploaded"
