#!/bin/sh
# Upload file: server.key
# Auto-generated by create-application
set -eu

upload_pre_start_file \
  "{{ upload_server_content }}" \
  "{{ upload_server_destination }}" \
  "server.key" \
  "{{ shared_volpath }}" \
  "{{ hostname }}" \
  "{{ uid }}" \
  "{{ gid }}" \
  "{{ mapped_uid }}" \
  "{{ mapped_gid }}"

upload_output_result "upload_server_uploaded"
