#!/bin/sh
# Upload file: enable-ssl.sh
# Auto-generated by create-application
set -eu

upload_pre_start_file \
  "{{ upload_enable_ssl_sh_content }}" \
  "{{ upload_enable_ssl_sh_destination }}" \
  "enable-ssl.sh" \
  "{{ shared_volpath }}" \
  "{{ hostname }}" \
  "{{ uid }}" \
  "{{ gid }}" \
  "{{ mapped_uid }}" \
  "{{ mapped_gid }}"

upload_output_result "upload_enable_ssl_sh_uploaded"
