#!/bin/sh
# Install the Samba on-start drop-in script.
#
# Creates /etc/lxc-oci-deployer/on_start.d/smbd.sh which handles:
# - Mirror configuration (Alpine/Debian)
# - Samba package installation (if not present)
# - User creation and password setup
# - Starting smbd and nmbd daemons
#
# The script is executed by the on_start_container dispatcher
# after each container restart, and runs immediately for initial setup.
#
# Requires:
#   - smb_user: Username for Samba authentication
#   - smb_password: Password for Samba authentication
#   - alpine_mirror: (optional) Alpine mirror URL
#   - debian_mirror: (optional) Debian mirror URL
#
# Output: errors to stderr only

SMB_USER="{{ smb_user }}"
SMB_PASSWORD="{{ smb_password }}"
ALPINE_MIRROR="{{ alpine_mirror }}"
DEBIAN_MIRROR="{{ debian_mirror }}"

SCRIPT_PATH="/etc/lxc-oci-deployer/on_start.d/smbd.sh"

# Part 1: Write header with baked-in values (expanded from template)
cat > "$SCRIPT_PATH" <<EOF
#!/bin/sh
# Samba service - install, configure and start
# Generated by oci-lxc-deployer
# Runs on every container start via the on_start_container dispatcher.

SMB_USER="$SMB_USER"
SMB_PASSWORD="$SMB_PASSWORD"
ALPINE_MIRROR="$ALPINE_MIRROR"
DEBIAN_MIRROR="$DEBIAN_MIRROR"
EOF

# Part 2: Append script body (no variable expansion)
cat >> "$SCRIPT_PATH" << 'SMBEOF'

# --- If smbd is already running, nothing to do ---
if pgrep -x smbd >/dev/null 2>&1; then
  echo "smbd already running" >&2
  exit 0
fi

# --- Detect OS ---
OS_TYPE=""
if [ -f /etc/os-release ]; then
  . /etc/os-release
  OS_TYPE="$ID"
elif command -v apk >/dev/null 2>&1; then
  OS_TYPE="alpine"
elif command -v apt-get >/dev/null 2>&1; then
  OS_TYPE="debian"
fi

# --- Install samba if not present ---
if ! command -v smbd >/dev/null 2>&1; then
  echo "Installing samba..." >&2

  case "$OS_TYPE" in
    alpine)
      if [ -n "$ALPINE_MIRROR" ]; then
        ALPINE_VERSION=$(cut -d. -f1,2 < /etc/alpine-release 2>/dev/null)
        if [ -n "$ALPINE_VERSION" ]; then
          cat > /etc/apk/repositories <<MIRROREOF
${ALPINE_MIRROR}/v${ALPINE_VERSION}/main
${ALPINE_MIRROR}/v${ALPINE_VERSION}/community
MIRROREOF
          echo "Set Alpine mirror: $ALPINE_MIRROR" >&2
        fi
      fi
      apk update >&2
      apk add --no-cache samba >&2
      ;;
    debian|ubuntu)
      if [ -n "$DEBIAN_MIRROR" ]; then
        if [ -f /etc/os-release ]; then
          . /etc/os-release
          CODENAME="$VERSION_CODENAME"
        fi
        if [ -z "$CODENAME" ]; then
          CODENAME="stable"
        fi
        cat > /etc/apt/sources.list <<MIRROREOF
deb ${DEBIAN_MIRROR} ${CODENAME} main
deb ${DEBIAN_MIRROR} ${CODENAME}-updates main
MIRROREOF
        echo "Set Debian mirror: $DEBIAN_MIRROR" >&2
      fi
      export DEBIAN_FRONTEND=noninteractive
      apt-get update -qq >&2
      apt-get install -y --no-install-recommends samba >&2
      ;;
  esac
fi

# --- Create directories ---
mkdir -p /etc/samba
mkdir -p /var/lib/samba/private

# --- Create user if not exists ---
if [ -n "$SMB_USER" ] && ! id "$SMB_USER" >/dev/null 2>&1; then
  echo "Creating user '$SMB_USER'..." >&2
  if command -v adduser >/dev/null 2>&1; then
    adduser -D -H -s /sbin/nologin "$SMB_USER" >&2
  elif command -v useradd >/dev/null 2>&1; then
    useradd -r -M -s /usr/sbin/nologin "$SMB_USER" >&2
  fi
fi

# --- Set samba password if user has no samba entry ---
if [ -n "$SMB_USER" ] && [ -n "$SMB_PASSWORD" ]; then
  if ! pdbedit -L 2>/dev/null | grep -q "^${SMB_USER}:"; then
    echo "Setting Samba password for '$SMB_USER'..." >&2
    printf '%s\n%s\n' "$SMB_PASSWORD" "$SMB_PASSWORD" | smbpasswd -a -s "$SMB_USER" >&2
    smbpasswd -e "$SMB_USER" >&2
  fi
fi

# --- Start daemons ---
echo "Starting smbd..." >&2
smbd -D >&2
echo "Starting nmbd..." >&2
nmbd -D >&2
SMBEOF

chmod 700 "$SCRIPT_PATH"
echo "Installed Samba on-start script: ${SCRIPT_PATH}" >&2

# Run immediately for initial installation
echo "Running initial Samba setup..." >&2
"$SCRIPT_PATH"
