#!/bin/sh
# Install the JWKS-refresh on-start drop-in for a PostgREST + Zitadel app.
#
# Writes /etc/proxvex/on_start.d/jwks-refresh.sh which, on every container
# start, fetches the Zitadel JWKS (RS256 public keys) to the file PostgREST
# reads via PGRST_JWT_SECRET=@/jwks/jwks.json, then signals PostgREST to
# reload its config (SIGUSR2) so rotated keys take effect without a restart.
#
# This is the runtime half of the zitadel-pgrst-auth integration: the
# 331-provision-auth-rls template installs the DB-side `auth` core; this hook
# keeps PostgREST's JWT verification keys current. No Zitadel action, no
# nginx-Lua, no shared secret.
#
# Requires (oidc stacktype provides ZITADEL_URL):
#   - ZITADEL_URL: full base URL of the Zitadel API (e.g. https://zitadel:8443)
#
# Output: errors to stderr only.

ZITADEL_URL="{{ ZITADEL_URL }}"

SCRIPT_PATH="/etc/proxvex/on_start.d/jwks-refresh.sh"
mkdir -p "$(dirname "$SCRIPT_PATH")"

cat > "$SCRIPT_PATH" <<EOF
#!/bin/sh
# JWKS refresh — generated by proxvex; runs on every container start via the
# on_start_container dispatcher. Fetches the Zitadel JWKS for PostgREST.

ZITADEL_URL="$ZITADEL_URL"
EOF

cat >> "$SCRIPT_PATH" <<'EOF'
JWKS_DIR=/jwks
JWKS_FILE="$JWKS_DIR/jwks.json"
mkdir -p "$JWKS_DIR"

[ -n "$ZITADEL_URL" ] || { echo "jwks-refresh: ZITADEL_URL empty, skip" >&2; exit 0; }

# Wait for Zitadel, then write the JWKS atomically.
i=0
while [ "$i" -lt 60 ]; do
  if curl -sf "$ZITADEL_URL/oauth/v2/keys" -o "$JWKS_FILE.tmp" 2>/dev/null; then
    mv "$JWKS_FILE.tmp" "$JWKS_FILE"
    echo "jwks-refresh: wrote $JWKS_FILE" >&2
    break
  fi
  i=$((i+1)); sleep 2
done
[ -f "$JWKS_FILE" ] || { echo "jwks-refresh: could not fetch JWKS" >&2; exit 0; }

# Tell PostgREST to reload config (re-reads PGRST_JWT_SECRET=@file) so a
# rotated key set is picked up without a restart. Best-effort.
if command -v pkill >/dev/null 2>&1; then
  pkill -USR2 -x postgrest 2>/dev/null || true
fi
EOF

chmod +x "$SCRIPT_PATH"
echo "jwks-refresh on-start drop-in installed at $SCRIPT_PATH" >&2
