#!/bin/sh
# Upload file: server.cert
# Auto-generated by create-application
set -eu

upload_pre_start_file \
  "{{ upload_server_cert_content }}" \
  "{{ upload_server_cert_destination }}" \
  "server.cert" \
  "{{ shared_volpath }}" \
  "{{ hostname }}" \
  "{{ uid }}" \
  "{{ gid }}" \
  "{{ mapped_uid }}" \
  "{{ mapped_gid }}"

upload_output_result "upload_server_cert_uploaded"
