#!/bin/sh
# Upload file: ssl.cnf
# Auto-generated by create-application
set -eu

upload_pre_start_file \
  "{{ upload_ssl_cnf_content }}" \
  "{{ upload_ssl_cnf_destination }}" \
  "ssl.cnf" \
  "{{ shared_volpath }}" \
  "{{ hostname }}" \
  "{{ uid }}" \
  "{{ gid }}" \
  "{{ mapped_uid }}" \
  "{{ mapped_gid }}"

upload_output_result "upload_ssl_cnf_uploaded"
